### ISSUE TITLE
Submiting Pre work assignment

### ISSUE THREAD

**Issue by dunghuynh1990** [dunghuynh1990/TipsCalculator#1]
Here my complete prework assignment, thank you!
cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Swift submission, dunghuynh1990!

 :yum: Everything looks good with the format of your submission. We'll be reviewing your submission soon!

**Comment by coderschoolreview** [comment]
:+1:  Great job with the Tip Calculator! 

### Quick Comments:
- Your app UI looks good :smile:  
- Good usage of `NSUserDefaults` but it's hard for the user to know that after editing the default percentage, user needs to tap outside to get that number saved.
- Is this a typo where maximum is actually minimum and vice versa?

<img width="313" alt="screen shot 2016-03-01 at 1 20 55 am" src="https://cloud.githubusercontent.com/assets/15702670/13404363/dfa73216-df4b-11e5-9ae0-9ab8ea18a19f.png">
- You shouldn't let the user enter invalid number, should you? Your app crashed when I type 2 `..` Another case it can crash is when the app first load, I just switch the percentage.

<img width="507" alt="screen shot 2016-03-01 at 1 07 21 am" src="https://cloud.githubusercontent.com/assets/15702670/13404453/3dba4abe-df4c-11e5-8599-9766c31ac929.png">

**Comment by dunghuynh1990** [comment]
Thanks for the review about my Tips Calculator.

I knew to coderschool.vn from an introduction of my friend on last Friday
night and I decided to give it a try. Although I had a lot of planned
activities for the weekends but I try my best to finish the assignment in
the last couple of hours before the deadline submission. I will fix these
bugs and update on my github ASAP. Once again, thank you for taking your
time to review my app.

Best regards.

Huynh Tri Dung.

Vào Th 3, 1 thg 3, 2016 vào lúc 01:23 coderschoolreview <
notifications@github.com> đã viết:

**Comment by harley** [comment]
@dunghuynh1990 hello -- have you got the chance to improve the app? /cc @coderschoolreview
